global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /
    static_configs:
      - targets: ['192.168.1.223:8887','192.168.10.103:8887']
